---
name: Repository Updater

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: ["update"]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout external repository
        uses: actions/checkout@v4
        with:
          repository: staerk-ha-addons/repository
          path: external-repo
          token: ${{ secrets.PAT_TOKEN }}

      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: current-repo

      - name: Copy READMEs
        run: |
          mkdir -p current-repo/profile
          cp -f external-repo/README.md current-repo/README.md
          cp -f external-repo/README.md current-repo/profile/README.md

      - name: Commit and push if changed
        working-directory: current-repo
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md profile/README.md
          git diff --quiet && git diff --staged --quiet || \
          (git commit -m ":tada: Update README files" && git push)

      - name: Cleanup
        if: always()
        run: |
          rm -rf external-repo
          rm -rf current-repo
